spring.application.name=auth-service

spring.h2.console.path =/h2-console
spring.datasource.url =jdbc:h2:mem:authdb
spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform =org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

server.port = 4001
logging.level.root=info

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

app.admin.email=admin@propertyapp.com
app.admin.password=Admin@1234
app.admin.firstname=Super
app.admin.lastname=Admin

#Email config
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App URL ? used in verification link
app.url=http://localhost:4001

# gRPC server port
grpc.server.port=9001