from qdrant_client import QdrantClient
from qdrant_client.models import (
    Distance,
    VectorParams,
    PointStruct,
    Filter,
    FieldCondition,
    MatchValue
)
from config.settings import (
    QDRANT_HOST,
    QDRANT_PORT,
    QDRANT_COLLECTION_NAME,
    EMBEDDING_VECTOR_SIZE,
)

class VectorDBService:
    def __init__(self):
        """
       Connects to Qdrant and ensures the collection exists on startup.
       """
        print(f"Connecting to Qdrant at {QDRANT_HOST}:{QDRANT_PORT}...")
        self.client     = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)
        self.collection = QDRANT_COLLECTION_NAME
        self._ensure_collection()
        print(f"Connected. Using collection: '{self.collection}'")

    def _ensure_collection(self):
        """
       Creates the collection if it does not already exist.
       Uses cosine similarity — best choice for text embeddings.
       """
        existing = [c.name for c in self.client.get_collections().collections]

        if self.collection not in existing:
            print(f"Collection '{self.collection}' not found. Creating...")
            self.client.create_collection(
                collection_name=self.collection,
                vectors_config=VectorParams(
                    size=EMBEDDING_VECTOR_SIZE,
                    distance=Distance.COSINE,
                ),
            )
            print(f"Collection '{self.collection}' created.")

    def upsert_point(self, point_id: str, vector: list[float], payload: dict):
        """
        Inserts or updates a single vector point with its metadata.

        Args:
            point_id: Unique ID from the microservice (UUID string).
            vector:   Embedding generated by AIProcessorService.
            payload:  Metadata stored alongside the vector.
        """
        self.client.upsert(
            collection_name=self.collection,
            points=[
                PointStruct(
                    id=point_id,
                    vector=vector,
                    payload=payload,
                )
            ],
        )

    def delete_point(self, point_id: str):
        """
        Deletes a single point by its ID.
        """
        self.client.delete(
            collection_name=self.collection,
            points_selector=[point_id],
        )

    def delete_reviews_by_property(self, property_id: str):
        """
       Deletes all review vectors linked to a given property.
       Filters by both type=review AND propertyId for safety.
       """
        self.client.delete(
            collection_name=self.collection,
            points_selector=Filter(
                must=[
                    FieldCondition(key="type",       match=MatchValue(value="review")),
                    FieldCondition(key="propertyId", match=MatchValue(value=property_id)),
                ]
            ),
        )

    def search(self, query_vector: list[float], top_k: int = 5, filters: Filter = None) -> list:
        """
        Performs a semantic similarity search against the collection.

        Args:
            query_vector: The embedded query vector to search with.
            top_k:        Number of closest results to return.
            filters:      Optional Qdrant Filter to narrow results.

        Returns:
            A list of ScoredPoint results from Qdrant.
        """
        results = self.client.query_points(
            collection_name=self.collection,
            query=query_vector,
            limit=top_k,
            query_filter=filters,
        )
        return results.points


