apiVersion: v1
kind: ConfigMap
metadata:
  name: rental-config
  namespace: smart-rental
data:
  APP_URL: "http://api.rental.local"
  CORS_ALLOWED_ORIGINS: "http://rental.local"
  MAIL_HOST: "mailpit"
  MAIL_PORT: "1025"