apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: smart-rental
type: Opaque
stringData:
  JWT_SECRET: "bXktc3VwZXItc2VjcmV0LWtleS1tdXN0LWJlLWF0LWxlYXN0LTMyLWNoYXJz"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_USERNAME: "kividukividu@gmail.com"
  MAIL_PASSWORD: "nias tmyp vcin ukkk"
  CLOUDINARY_CLOUD_NAME: "dzeavxbm9"
  CLOUDINARY_API_KEY: "243541545994579"
  CLOUDINARY_API_SECRET: "v1w1lABqSLtneneiN7U_b1JQXxE"
  AUTH_DB_USER: "admin"
  AUTH_DB_PASSWORD: "pw"
  PROPERTY_DB_USER: "admin_user"
  PROPERTY_DB_PASSWORD: "password"
  REVIEW_DB_USER: "admin_user"
  REVIEW_DB_PASSWORD: "password"
