spring.application.name=property-service

spring.h2.console.path =/h2-console
spring.datasource.url =jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=admin_viewer
spring.datasource.password=password

spring.jpa.database-platform =org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

server.port = 4000
logging.level.root=info

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# Multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# tells property-service where auth-service gRPC is
grpc.client.auth-service.address=static://localhost:9001
grpc.client.auth-service.negotiation-type=plaintext

jwt.secret=${JWT_SECRET}