spring.application.name=review-service
server.port=4002

# H2 Database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:reviewdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update


# gRPC clients
grpc.client.auth-service.address=static://localhost:9001
grpc.client.auth-service.negotiation-type=plaintext

grpc.client.property-service.address=static://localhost:9002
grpc.client.property-service.negotiation-type=plaintext

jwt.secret=${JWT_SECRET}


